### ISSUE TITLE
Expired Discord Community Invite Link

### ISSUE THREAD

**Issue by khaleb-dev** [outerbase/studio#195]
When I try to join the Discord community found on the product website, I get an invalid/expired invite link error on Discord.

Here is the invite link I used: [https://discord.gg/CvfB3nzK](https://discord.gg/CvfB3nzK)

Here is where I found the link: [https://studio.outerbase.com/](https://studio.outerbase.com/)

**Comment by invisal** [comment]
@khaleb-dev sorry. I just updated the new Discord link now. Thanks for report

**Comment by khaleb-dev** [comment]
@invisal still the same thing with the new link: [https://discord.com/invite/t8twVN5KdG](https://discord.com/invite/t8twVN5KdG)

![image](https://github.com/user-attachments/assets/dde92925-1dd8-4f86-b1bc-3156fc628938)

**Comment by invisal** [comment]
@khaleb-dev that's truly strange. I put the that link as never expired. Can you try this Discord link: https://discord.gg/7zfESKF6Qp

**Comment by khaleb-dev** [comment]
Alright, this worked: [https://discord.gg/7zfESKF6Qp](https://discord.gg/7zfESKF6Qp)
